backend:
  name: github
  repo: https://github.com/EBK-CORPORATIONS/blogging-cms
  branch: main
  auth_type: implicit
  
  

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "posts"
    label: "Posts"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
